image:
  repository: ghcr.io/sre-helmcode/oncall-slack-bot
  tag: "1.0.1"
  pullPolicy: IfNotPresent

postgres:
  enabled: true
  useAppBinding: false
  dbName: oncall
  user: oncalluser
  password: oncallpass
  storage: 1Gi
  version: "15.12"
  storageClassName: do-block-storage

app:
  envFromAppBinding: true
  appBindingSecret: "oncall-postgres-appbinding"

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: oncall.helmcode.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: oncall-helmcode-tls
      hosts:
        - oncall.helmcode.com

imagePullSecrets:
  - name: ghcr-creds