# Imagen del bot
image:
  repository: ghcr.io/sre-helmcode/oncall-slack-bot
  tag: "1.0.3"
  pullPolicy: IfNotPresent
  imagePullSecrets: ghcr-creds

# Vault configuration
vault:
  connectionRef: vault-connection
  address: https://vault.helmcode.com
  skipTLSVerify: false

  authRef: vault-auth
  kubernetesAuthMount: kubernetes
  kubernetesRole: vault-auth
  serviceAccountName: oncall-bot-sa
  audiences:
    - vault

  staticSecretRef: oncall-slack-bot-vault-secret
  mount: oncall
  destinationSecretName: oncall-slack-bot-env-secret
  refreshAfter: 1m

# Recursos opcionales
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Replicas del bot
replicaCount: 1