postgres:
  enabled: true
  useAppBinding: true
  dbName: oncall
  user: oncalluser
  password: oncallpass
  storage: 1Gi
  version: "15.12"
  storageClassName: do-block-storage

app:
  envFromAppBinding: true
  appBindingSecret: oncall-postgres-appbinding