apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oncall-slack-bot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/helmcode/oncall-slack-bot.git
    targetRevision: main
    path: helm/oncall-slack-bot
  destination:
    server: https://kubernetes.default.svc
    namespace: oncall
  syncPolicy:
    automated:
      prune: true
      selfHeal: true