{{- if and .Values.postgres.enabled .Values.postgres.useAppBinding }}
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: {{ include "oncall-slack-bot.fullname" . }}-appbinding
spec:
  type: postgres
  secret:
    name: {{ include "oncall-slack-bot.fullname" . }}-pg-secret
  clientConfig:
    url: "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ include "oncall-slack-bot.fullname" . }}-pg:5432/{{ .Values.postgres.dbName }}"
{{- end }}