apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oncall-slack-bot.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "oncall-slack-bot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "oncall-slack-bot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "oncall-slack-bot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets }}
      containers:
        - name: bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            {{- if .Values.postgres.useAppBinding }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.appBindingSecret }}
                  key: uri
            {{- else }}
            - name: DB_HOST
              value: "{{ include "oncall-slack-bot.fullname" . }}-pg"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "{{ .Values.postgres.dbName }}"
            - name: DB_USER
              value: "{{ .Values.postgres.user }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "oncall-slack-bot.fullname" . }}-pg-secret
                  key: password
            {{- end }}
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "oncall-slack-bot.fullname" . }}-slack-secret
                  key: SLACK_BOT_TOKEN
            - name: SLACK_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "oncall-slack-bot.fullname" . }}-slack-secret
                  key: SLACK_APP_TOKEN