apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oncall-slack-bot.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "oncall-slack-bot.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "oncall-slack-bot.name" . }}
    spec:
      serviceAccountName: {{ .Values.vault.serviceAccountName | default "oncall-bot-sa" }}
      containers:
        - name: bot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: {{ .Values.vault.destinationSecretName | default "oncall-slack-bot-env-secret" }}