apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oncall-slack-bot.fullname" . }}-pg-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: "{{ .Values.postgres.user }}"
  password: "{{ .Values.postgres.password }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oncall-slack-bot.fullname" . }}-appbinding
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
 uri: "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ include "oncall-slack-bot.fullname" . }}-pg.{{ .Release.Namespace }}.svc:5432/{{ .Values.postgres.dbName }}"