apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vault.serviceAccountName | default "oncall-bot-sa" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "oncall-slack-bot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "oncall-slack-bot.chart" . }}