apiVersion: v1
kind: Service
metadata:
  name: {{ include "oncall-slack-bot.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "oncall-slack-bot.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080