  apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: {{ .Values.vault.connectionRef | default "vault-connection" }}
spec:
  address: {{ .Values.vault.address | default "https://vault.helmcode.com" }}
  skipTLSVerify: {{ .Values.vault.skipTLSVerify | default false }}