apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ .Values.vault.authRef | default "vault-auth" }}
spec:
  method: kubernetes
  mount: {{ .Values.vault.kubernetesAuthMount | default "kubernetes" }}
  kubernetes:
    role: {{ .Values.vault.kubernetesRole | default "vault-auth" }}
    serviceAccount: {{ .Values.vault.serviceAccountName | default "oncall-bot-sa" }}
    audiences:
{{- range .Values.vault.audiences }}
      - {{ . }}
{{- end }}
  vaultConnectionRef: {{ .Values.vault.connectionRef | default "vault-connection" }}
