apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.vault.staticSecretRef | default "oncall-slack-bot-vault-secret" }}
spec:
  type: kv-v2
  hmacSecretData: true
  mount: {{ .Values.vault.mount | default "oncall" }}
  destination:
    name: {{ .Values.vault.destinationSecretName | default "oncall-slack-bot-env-secret" }}
    create: true
  refreshAfter: {{ .Values.vault.refreshAfter | default "1m" }}
  vaultAuthRef: {{ .Values.vault.authRef | default "vault-auth" }}