apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "anyformat.fullname" . }}-vault-secret
  labels:
    {{- include "anyformat.labels" . | nindent 4 }}
spec:
  type: kv-v2
  hmacSecretData: true
  mount: {{ .Values.vault.mount | default "anyformat" }}
  {{- if .Values.vault.path }}
  path: {{ .Values.vault.path }}
  {{- else }}
  path: {{ .Values.vault.environment | default "dev" }}
  {{- end }}
  destination:
    name: {{ include "anyformat.fullname" . }}-env-secret
    create: true
    annotations:
      {{- if .Values.vault.annotations }}
      {{- toYaml .Values.vault.annotations | nindent 6 }}
      {{- end }}
  refreshAfter: {{ .Values.vault.refreshAfter | default "1m" }}
  vaultAuthRef: {{ .Values.vault.authRef | default "vault-auth" }}
  {{- if and (hasKey .Values.vault "rolloutRestart") .Values.vault.rolloutRestart }}
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ include "anyformat.fullname" . }}
  {{- end }}